import type { Page } from "playwright";
import { BrowserSessionManager } from "@nigs/browser-playwright";
import type { RunContext } from "@nigs/core";
import { filterOrganicYouTubeResults, type YoutubeSearchResult } from "./filter.js";

const LAST_SEARCH_RESULTS_KEY = "youtube:last-search-results";

export interface YoutubeVideoArtifact extends YoutubeSearchResult {
  transcriptText: string | null;
}

export interface YoutubeShortArtifact {
  platform: "youtube";
  position: number;
  url: string;
  videoId: string | null;
  title: string | null;
  caption: string | null;
  hashtags: string[];
  creatorName: string | null;
  creatorHandle: string | null;
  creatorUrl: string | null;
  likeCountText: string | null;
  commentCountText: string | null;
  viewCountText: string | null;
  collectedAt: string;
}

export interface YoutubeShortTranscriptSegment {
  startMs: number;
  durationMs: number | null;
  text: string;
}

export interface YoutubeShortTranscriptArtifact extends YoutubeShortArtifact {
  transcriptText: string | null;
  transcriptSegments: YoutubeShortTranscriptSegment[];
  transcriptLanguage: string | null;
  transcriptTrackName: string | null;
  transcriptSource: "captions" | "unavailable";
  transcriptError: string | null;
}

interface YoutubeCaptionTrack {
  baseUrl: string;
  languageCode: string | null;
  name: string | null;
  kind: string | null;
  isAutoGenerated: boolean;
}

function formatDuration(seconds: number): string {
  const wholeSeconds = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(wholeSeconds / 3600);
  const minutes = Math.floor((wholeSeconds % 3600) / 60);
  const remainingSeconds = wholeSeconds % 60;

  if (hours > 0) {
    return [hours, minutes, remainingSeconds]
      .map((value, index) => (index === 0 ? String(value) : String(value).padStart(2, "0")))
      .join(":");
  }

  return [minutes, remainingSeconds]
    .map((value, index) => (index === 0 ? String(value) : String(value).padStart(2, "0")))
    .join(":");
}

async function tryClick(locators: Array<() => Promise<void>>): Promise<boolean> {
  for (const action of locators) {
    try {
      await action();
      return true;
    } catch {
      // Keep trying other locator strategies.
    }
  }

  return false;
}

async function acceptConsent(page: Page): Promise<void> {
  await tryClick([
    async () => {
      const button = page.getByRole("button", { name: /accept all/i }).first();
      await button.click({ timeout: 2_000 });
    },
    async () => {
      const button = page.getByRole("button", { name: /i agree/i }).first();
      await button.click({ timeout: 2_000 });
    },
    async () => {
      const button = page.getByRole("button", { name: /agree/i }).first();
      await button.click({ timeout: 2_000 });
    }
  ]);
}

async function extractSearchResults(page: Page): Promise<YoutubeSearchResult[]> {
  const rawResults = await page.locator("ytd-video-renderer").evaluateAll((cards) =>
    cards.map((card) => {
      const titleLink = card.querySelector<HTMLAnchorElement>("#video-title");
      const metadata = Array.from(card.querySelectorAll("#metadata-line span"))
        .map((node) => node.textContent?.replace(/\s+/g, " ").trim() ?? "")
        .filter(Boolean);
      const description = Array.from(
        card.querySelectorAll(
          "#description-text, #description-text-inline-expander, yt-formatted-string.metadata-snippet-text"
        )
      )
        .map((node) => node.textContent?.replace(/\s+/g, " ").trim() ?? "")
        .find(Boolean);
      const duration = card
        .querySelector("ytd-thumbnail-overlay-time-status-renderer span")
        ?.textContent?.replace(/\s+/g, " ")
        .trim();
      const href = titleLink?.href ?? titleLink?.getAttribute("href") ?? "";

      return {
        title: titleLink?.textContent?.replace(/\s+/g, " ").trim() ?? "",
        url: href.startsWith("http") ? href : new URL(href, location.origin).toString(),
        channel:
          card
            .querySelector("#channel-name a, ytd-channel-name a")
            ?.textContent?.replace(/\s+/g, " ")
            .trim() ?? null,
        publishedText: metadata[1] ?? null,
        durationText: duration || null,
        descriptionText: description ?? null,
        viewsText: metadata[0] ?? null
      };
    })
  );

  return rawResults;
}

async function expandDescription(page: Page): Promise<void> {
  await tryClick([
    async () => {
      const button = page.locator("#expand").first();
      await button.click({ timeout: 2_000 });
    },
    async () => {
      const button = page.getByRole("button", { name: /more/i }).first();
      await button.click({ timeout: 2_000 });
    }
  ]);
}

async function waitForAnyVisibleSelector(
  page: Page,
  selectors: string[],
  timeoutMs: number
): Promise<string | null> {
  const startedAt = Date.now();

  while (Date.now() - startedAt < timeoutMs) {
    for (const selector of selectors) {
      const locator = page.locator(selector).first();
      try {
        if (await locator.isVisible({ timeout: 500 })) {
          return selector;
        }
      } catch {
        // Keep polling other candidates.
      }
    }

    await page.waitForTimeout(250);
  }

  return null;
}

async function waitForYouTubeWatchPageReady(page: Page): Promise<void> {
  await page.waitForURL(/\/watch\b/, { timeout: 20_000 });

  const visibleTitleSelector = await waitForAnyVisibleSelector(
    page,
    [
      "ytd-watch-metadata h1 yt-formatted-string",
      "ytd-watch-metadata h1",
      "#title h1 yt-formatted-string",
      "#title h1"
    ],
    30_000
  );

  if (visibleTitleSelector) {
    return;
  }

  const fallbackTitle = await page.evaluate(() => {
    const selectors = [
      "ytd-watch-metadata h1 yt-formatted-string",
      "ytd-watch-metadata h1",
      "#title h1 yt-formatted-string",
      "#title h1"
    ];

    for (const selector of selectors) {
      const elements = Array.from(document.querySelectorAll<HTMLElement>(selector));
      for (const element of elements) {
        const text = element.innerText?.replace(/\s+/g, " ").trim();
        const style = window.getComputedStyle(element);
        if (text && style.display !== "none" && style.visibility !== "hidden") {
          return text;
        }
      }
    }

    return null;
  });

  if (fallbackTitle) {
    return;
  }

  throw new Error("Timed out waiting for a visible YouTube watch-page title.");
}

async function extractTranscript(page: Page): Promise<string | null> {
  const opened = await tryClick([
    async () => {
      const button = page.getByText("Show transcript", { exact: false }).first();
      await button.click({ timeout: 2_000 });
    },
    async () => {
      const menuButton = page.locator('button[aria-label*="More actions"]').first();
      await menuButton.click({ timeout: 2_000 });
      const transcriptButton = page.getByText("Show transcript", { exact: false }).first();
      await transcriptButton.click({ timeout: 2_000 });
    }
  ]);

  if (!opened) {
    return null;
  }

  try {
    await page.locator("ytd-transcript-segment-renderer").first().waitFor({
      state: "visible",
      timeout: 5_000
    });
  } catch {
    return null;
  }

  const transcript = await page.locator("ytd-transcript-segment-renderer").evaluateAll((segments) =>
    segments
      .map((segment) => {
        const timestamp =
          segment
            .querySelector('[class*="timestamp"], [id*="timestamp"]')
            ?.textContent?.replace(/\s+/g, " ")
            .trim() ?? "";
        const text =
          segment
            .querySelector('[class*="segment-text"], [id*="segment-text"]')
            ?.textContent?.replace(/\s+/g, " ")
            .trim() ?? "";
        return [timestamp, text].filter(Boolean).join(" ");
      })
      .filter(Boolean)
      .join("\n")
  );

  return transcript || null;
}

function dedupeShorts(shorts: YoutubeShortArtifact[]): YoutubeShortArtifact[] {
  const seen = new Set<string>();
  const deduped: YoutubeShortArtifact[] = [];

  for (const short of shorts) {
    const key = short.url.includes("/shorts/") ? short.url : `${short.title}:${short.hashtags.join(",")}`;
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    deduped.push(short);
  }

  return deduped;
}

function normalizeFingerprintText(value: string | null | undefined): string {
  return (value ?? "").replace(/\s+/g, " ").trim().toLowerCase();
}

function looksLikeStaleShortMetadata(
  previous: YoutubeShortArtifact | undefined,
  current: YoutubeShortArtifact
): boolean {
  if (!previous || previous.videoId === current.videoId || previous.url === current.url) {
    return false;
  }

  const sameTitle = normalizeFingerprintText(previous.title) === normalizeFingerprintText(current.title);
  const sameCaption = normalizeFingerprintText(previous.caption) === normalizeFingerprintText(current.caption);
  const sameCreator =
    normalizeFingerprintText(previous.creatorHandle) === normalizeFingerprintText(current.creatorHandle) ||
    normalizeFingerprintText(previous.creatorName) === normalizeFingerprintText(current.creatorName);
  const sameLike = normalizeFingerprintText(previous.likeCountText) === normalizeFingerprintText(current.likeCountText);
  const sameHashtags =
    previous.hashtags.map(normalizeFingerprintText).join(",") === current.hashtags.map(normalizeFingerprintText).join(",");

  return sameCreator && (sameTitle || sameCaption) && (sameLike || sameHashtags);
}

function decodeXmlText(value: string): string {
  return value
    .replace(/&#(\d+);/g, (_match, code: string) => String.fromCodePoint(Number(code)))
    .replace(/&#x([\da-f]+);/gi, (_match, code: string) => String.fromCodePoint(Number.parseInt(code, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

function normalizeCaptionText(value: string | null | undefined): string {
  return (value ?? "").replace(/\s+/g, " ").trim();
}

function buildShortFromUrl(url: string, position: number): YoutubeShortArtifact {
  const normalizedUrl = new URL(url).toString();
  const videoId = normalizedUrl.match(/\/shorts\/([^/?#]+)/)?.[1] ?? null;

  return {
    platform: "youtube",
    position,
    url: normalizedUrl,
    videoId,
    title: null,
    caption: null,
    hashtags: [],
    creatorName: null,
    creatorHandle: null,
    creatorUrl: null,
    likeCountText: null,
    commentCountText: null,
    viewCountText: null,
    collectedAt: new Date().toISOString()
  };
}

async function openShortsStart(page: Page, query?: string): Promise<void> {
  if (!query) {
    await page.goto("https://www.youtube.com/shorts", { waitUntil: "domcontentloaded" });
    await acceptConsent(page);
    return;
  }

  const searchUrl = new URL("https://www.youtube.com/results");
  searchUrl.searchParams.set("search_query", `${query} shorts`);
  await page.goto(searchUrl.toString(), { waitUntil: "domcontentloaded" });
  await acceptConsent(page);

  const shortsLink = page.locator('a[href*="/shorts/"]').first();
  await shortsLink.waitFor({ state: "visible", timeout: 20_000 });
  await shortsLink.click();
  await page.waitForURL(/\/shorts\//, { timeout: 20_000 });
}

async function waitForShortsReady(page: Page): Promise<void> {
  await page.waitForFunction(
    () =>
      window.location.pathname.startsWith("/shorts") &&
      Boolean(
        document.querySelector("ytd-reel-video-renderer") ||
          document.querySelector("video") ||
          document.querySelector('a[href*="/shorts/"]')
      ),
    { timeout: 30_000 }
  );
}

async function waitForShortsMetadata(page: Page): Promise<void> {
  try {
    await page.waitForFunction(
      () => {
        const normalizeText = (value: string | null | undefined): string =>
          (value ?? "").replace(/\s+/g, " ").trim();
        const isVisible = (element: Element): boolean => {
          const rect = element.getBoundingClientRect();
          const style = window.getComputedStyle(element);
          return rect.width > 0 && rect.height > 0 && style.display !== "none" && style.visibility !== "hidden";
        };
        const isCentered = (element: Element): boolean => {
          const rect = element.getBoundingClientRect();
          return (
            isVisible(element) &&
            rect.top < window.innerHeight * 0.6 &&
            rect.bottom > window.innerHeight * 0.4
          );
        };
        const containsVideoId = (element: ParentNode, videoId: string): boolean =>
          Array.from(element.querySelectorAll<HTMLAnchorElement>("a[href]")).some((anchor) => {
            const href = anchor.href || anchor.getAttribute("href") || "";
            return href.includes(`/shorts/${videoId}`) || href.includes(`watch?v=${videoId}`);
          });
        const pickText = (root: ParentNode, selectors: string[]): string | null => {
          for (const selector of selectors) {
            const elements = Array.from(root.querySelectorAll<HTMLElement>(selector));
            for (const element of elements) {
              if (!isVisible(element)) {
                continue;
              }
              const text = normalizeText(element.innerText || element.textContent);
              if (text) {
                return text;
              }
            }
          }
          return null;
        };
        const currentId = window.location.pathname.match(/\/shorts\/([^/?#]+)/)?.[1];
        if (!currentId) {
          return false;
        }

        const candidates = Array.from(document.querySelectorAll<HTMLElement>("ytd-reel-video-renderer"));
        const centered = candidates.filter(isCentered);
        const matching =
          centered.find((candidate) => containsVideoId(candidate, currentId)) ??
          centered.find((candidate) => candidate.matches("[is-active], [active]"));

        if (!matching || !containsVideoId(matching, currentId)) {
          return false;
        }

        return Boolean(
          pickText(matching, [
            "yt-reel-player-header-renderer h2",
            "yt-reel-player-header-renderer #title",
            "yt-reel-player-overlay-renderer #title",
            "h2",
            "#title",
            "yt-formatted-string#title",
            "yt-formatted-string[class*='title']"
          ])
        );
      },
      { timeout: 5_000 }
    );
  } catch {
    await page.waitForTimeout(1_000);
  }
}

async function extractActiveShort(page: Page, position: number): Promise<YoutubeShortArtifact | null> {
  return page.evaluate((itemPosition) => {
    const normalizeText = (value: string | null | undefined): string =>
      (value ?? "").replace(/\s+/g, " ").trim();
    const stripHashtags = (value: string): string =>
      value.replace(/#[\p{L}\p{N}_]+/gu, "").replace(/\s+/g, " ").trim();
    const hashtagsFrom = (value: string): string[] =>
      Array.from(new Set(value.match(/#[\p{L}\p{N}_]+/gu) ?? []));
    const firstText = (values: Array<string | null | undefined>): string | null => {
      for (const value of values) {
        const text = normalizeText(value);
        if (text) {
          return text;
        }
      }
      return null;
    };
    const isVisible = (element: Element): boolean => {
      const rect = element.getBoundingClientRect();
      const style = window.getComputedStyle(element);
      return rect.width > 0 && rect.height > 0 && style.display !== "none" && style.visibility !== "hidden";
    };
    const isCentered = (element: Element): boolean => {
      const rect = element.getBoundingClientRect();
      return (
        isVisible(element) &&
        rect.top < window.innerHeight * 0.6 &&
        rect.bottom > window.innerHeight * 0.4
      );
    };
    const containsVideoId = (element: ParentNode, videoId: string): boolean =>
      Array.from(element.querySelectorAll<HTMLAnchorElement>("a[href]")).some((anchor) => {
        const href = anchor.href || anchor.getAttribute("href") || "";
        return href.includes(`/shorts/${videoId}`) || href.includes(`watch?v=${videoId}`);
      });
    const pickText = (root: ParentNode, selectors: string[]): string | null => {
      for (const selector of selectors) {
        const element = Array.from(root.querySelectorAll<HTMLElement>(selector)).find(isVisible);
        const text = normalizeText(element?.innerText ?? element?.textContent);
        if (text) {
          return text;
        }
      }
      return null;
    };
    const findVisibleText = (root: ParentNode, selectors: string[]): string | null => {
      for (const selector of selectors) {
        const elements = Array.from(root.querySelectorAll<HTMLElement>(selector));
        for (const element of elements) {
          if (!isVisible(element)) {
            continue;
          }
          const text = normalizeText(element.innerText || element.textContent);
          if (text) {
            return text;
          }
        }
      }
      return null;
    };

    const candidates = Array.from(document.querySelectorAll<HTMLElement>("ytd-reel-video-renderer"));
    const currentVideoId = window.location.pathname.match(/\/shorts\/([^/?#]+)/)?.[1] ?? null;
    const centered = candidates.filter(isCentered);
    const active = currentVideoId
      ? centered.find((candidate) => containsVideoId(candidate, currentVideoId)) ?? null
      : centered.find((candidate) => candidate.matches("[is-active], [active]")) ?? centered[0] ?? null;

    if (!active || (currentVideoId && !containsVideoId(active, currentVideoId))) {
      return null;
    }

    const urlCandidate =
      window.location.pathname.startsWith("/shorts/") ? window.location.href :
      active.querySelector<HTMLAnchorElement>('a[href*="/shorts/"]')?.href ??
      window.location.href;
    const url = new URL(urlCandidate, window.location.origin).toString();
    const videoId = url.match(/\/shorts\/([^/?#]+)/)?.[1] ?? null;

    const titleCandidate = firstText([
      pickText(active, [
        "yt-reel-player-header-renderer h2",
        "yt-reel-player-header-renderer #title",
        "yt-reel-player-overlay-renderer #title",
        "h2",
        "#title",
        "yt-formatted-string#title",
        "yt-formatted-string[class*='title']"
      ])
    ]) ?? "";

    const hashtagText = Array.from(active.querySelectorAll<HTMLAnchorElement>('a[href*="/hashtag/"]'))
      .map((anchor) => normalizeText(anchor.innerText || anchor.textContent))
      .filter(Boolean)
      .join(" ");
    const combinedText = normalizeText(`${titleCandidate} ${hashtagText}`);
    const hashtags = hashtagsFrom(combinedText);
    const title = stripHashtags(titleCandidate) || titleCandidate;
    const creatorLink =
      active.querySelector<HTMLAnchorElement>('a[href^="/@"]') ??
      active.querySelector<HTMLAnchorElement>('a[href*="/channel/"]');
    const creatorUrl = creatorLink ? new URL(creatorLink.href, window.location.origin).toString() : null;
    const creatorHandle = creatorUrl?.match(/youtube\.com\/(@[^/?#]+)/)?.[1] ?? null;
    const creatorName =
      findVisibleText(active, [
        "ytd-channel-name",
        "#channel-name",
        "yt-reel-channel-bar-view-model",
        'a[href^="/@"]'
      ]) ??
      creatorHandle;
    const likeCountText = findVisibleText(active, [
      '[aria-label*="like" i]',
      'button[title*="like" i]',
      "like-button-view-model"
    ]);
    const commentCountText = findVisibleText(active, [
      '[aria-label*="comment" i]',
      'button[title*="comment" i]'
    ]);
    const viewCountText = findVisibleText(active, [
      '[aria-label*="view" i]',
      "#metadata-line",
      ".view-count"
    ]);

    if (!videoId || (!title && hashtags.length === 0)) {
      return null;
    }

    return {
      platform: "youtube",
      position: itemPosition,
      title,
      caption: titleCandidate || null,
      hashtags,
      url,
      videoId,
      creatorName,
      creatorHandle,
      creatorUrl,
      likeCountText,
      commentCountText,
      viewCountText,
      collectedAt: new Date().toISOString()
    };
  }, position);
}

async function extractStableActiveShort(
  page: Page,
  position: number,
  previousShort?: YoutubeShortArtifact
): Promise<YoutubeShortArtifact | null> {
  const deadline = Date.now() + 6_000;
  let lastCandidate: YoutubeShortArtifact | null = null;

  while (Date.now() < deadline) {
    await waitForShortsMetadata(page);
    const current = await extractActiveShort(page, position);
    if (!current) {
      await page.waitForTimeout(350);
      continue;
    }

    lastCandidate = current;
    if (!looksLikeStaleShortMetadata(previousShort, current)) {
      return current;
    }

    await page.waitForTimeout(500);
  }

  if (lastCandidate && !looksLikeStaleShortMetadata(previousShort, lastCandidate)) {
    return lastCandidate;
  }

  return null;
}

function parseJson3Transcript(value: unknown): YoutubeShortTranscriptSegment[] {
  if (!value || typeof value !== "object" || !Array.isArray((value as { events?: unknown[] }).events)) {
    return [];
  }

  return (value as { events: Array<Record<string, unknown>> }).events
    .map((event) => {
      const segs = Array.isArray(event.segs) ? event.segs : [];
      const text = normalizeCaptionText(
        segs
          .map((segment) =>
            segment && typeof segment === "object" && "utf8" in segment
              ? String((segment as { utf8?: unknown }).utf8 ?? "")
              : ""
          )
          .join("")
      );

      if (!text) {
        return null;
      }

      const startMs = typeof event.tStartMs === "number" ? event.tStartMs : 0;
      const durationMs = typeof event.dDurationMs === "number" ? event.dDurationMs : null;
      return { startMs, durationMs, text };
    })
    .filter((segment): segment is YoutubeShortTranscriptSegment => Boolean(segment));
}

function parseXmlTranscript(value: string): YoutubeShortTranscriptSegment[] {
  return Array.from(value.matchAll(/<text\b([^>]*)>([\s\S]*?)<\/text>/g))
    .map((match) => {
      const attributes = match[1] ?? "";
      const rawText = match[2] ?? "";
      const startSeconds = Number(attributes.match(/\bstart="([^"]+)"/)?.[1] ?? 0);
      const durationSeconds = attributes.match(/\bdur="([^"]+)"/)?.[1];
      const text = normalizeCaptionText(decodeXmlText(rawText.replace(/<[^>]+>/g, "")));

      if (!text) {
        return null;
      }

      return {
        startMs: Number.isFinite(startSeconds) ? Math.round(startSeconds * 1000) : 0,
        durationMs:
          durationSeconds !== undefined && Number.isFinite(Number(durationSeconds))
            ? Math.round(Number(durationSeconds) * 1000)
            : null,
        text
      };
    })
    .filter((segment): segment is YoutubeShortTranscriptSegment => Boolean(segment));
}

async function fetchCaptionTrack(track: YoutubeCaptionTrack): Promise<YoutubeShortTranscriptSegment[]> {
  const url = new URL(track.baseUrl);
  url.searchParams.set("fmt", "json3");

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Caption request failed with ${response.status}.`);
  }

  const text = await response.text();
  try {
    const parsed = JSON.parse(text);
    const jsonSegments = parseJson3Transcript(parsed);
    if (jsonSegments.length > 0) {
      return jsonSegments;
    }
  } catch {
    // Some caption tracks ignore fmt=json3 and return XML.
  }

  return parseXmlTranscript(text);
}

function rankCaptionTrack(track: YoutubeCaptionTrack): number {
  const language = track.languageCode?.toLowerCase() ?? "";
  const englishScore = language.startsWith("en") ? 0 : 10;
  const generatedScore = track.isAutoGenerated ? 2 : 0;
  return englishScore + generatedScore;
}

async function getCaptionTracksForCurrentShort(page: Page, videoId: string): Promise<YoutubeCaptionTrack[]> {
  return page.evaluate((targetVideoId) => {
    type RawCaptionTrack = {
      baseUrl?: string;
      languageCode?: string;
      kind?: string;
      vssId?: string;
      name?: {
        simpleText?: string;
        runs?: Array<{ text?: string }>;
      };
    };
    type RawPlayerResponse = {
      videoDetails?: {
        videoId?: string;
      };
      captions?: {
        playerCaptionsTracklistRenderer?: {
          captionTracks?: RawCaptionTrack[];
        };
      };
    };

    const trackName = (track: RawCaptionTrack): string | null =>
      track.name?.simpleText ??
      track.name?.runs?.map((run) => run.text ?? "").join("").trim() ??
      null;
    const readTracks = (response: RawPlayerResponse | null | undefined) => {
      if (!response || response.videoDetails?.videoId !== targetVideoId) {
        return [];
      }

      return response.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
    };
    const responses: RawPlayerResponse[] = [];
    const initialResponse = (window as unknown as { ytInitialPlayerResponse?: RawPlayerResponse }).ytInitialPlayerResponse;
    if (initialResponse) {
      responses.push(initialResponse);
    }

    for (const player of Array.from(document.querySelectorAll<HTMLElement>("#movie_player, .html5-video-player"))) {
      const maybeResponse = (player as unknown as { getPlayerResponse?: () => RawPlayerResponse | null }).getPlayerResponse?.();
      if (maybeResponse) {
        responses.push(maybeResponse);
      }
    }

    const seen = new Set<string>();
    return responses
      .flatMap(readTracks)
      .filter((track): track is RawCaptionTrack & { baseUrl: string } => Boolean(track.baseUrl))
      .map((track) => ({
        baseUrl: track.baseUrl,
        languageCode: track.languageCode ?? null,
        name: trackName(track),
        kind: track.kind ?? null,
        isAutoGenerated: track.kind === "asr" || Boolean(track.vssId?.startsWith("a."))
      }))
      .filter((track) => {
        if (seen.has(track.baseUrl)) {
          return false;
        }
        seen.add(track.baseUrl);
        return true;
      });
  }, videoId);
}

async function attachShortTranscript(
  page: Page,
  short: YoutubeShortArtifact
): Promise<YoutubeShortTranscriptArtifact> {
  if (!short.videoId) {
    return {
      ...short,
      transcriptText: null,
      transcriptSegments: [],
      transcriptLanguage: null,
      transcriptTrackName: null,
      transcriptSource: "unavailable",
      transcriptError: "Short URL did not include a video id."
    };
  }

  const tracks = (await getCaptionTracksForCurrentShort(page, short.videoId)).sort(
    (left, right) => rankCaptionTrack(left) - rankCaptionTrack(right)
  );
  if (tracks.length === 0) {
    return {
      ...short,
      transcriptText: null,
      transcriptSegments: [],
      transcriptLanguage: null,
      transcriptTrackName: null,
      transcriptSource: "unavailable",
      transcriptError: "No caption tracks were exposed by YouTube for this Short."
    };
  }

  let lastError: string | null = null;
  for (const track of tracks) {
    try {
      const transcriptSegments = await fetchCaptionTrack(track);
      const transcriptText = normalizeCaptionText(transcriptSegments.map((segment) => segment.text).join(" "));
      if (transcriptText) {
        return {
          ...short,
          transcriptText,
          transcriptSegments,
          transcriptLanguage: track.languageCode,
          transcriptTrackName: track.name,
          transcriptSource: "captions",
          transcriptError: null
        };
      }
      lastError = "Caption track was empty.";
    } catch (error) {
      lastError = error instanceof Error ? error.message : "Unknown caption fetch failure.";
    }
  }

  return {
    ...short,
    transcriptText: null,
    transcriptSegments: [],
    transcriptLanguage: null,
    transcriptTrackName: null,
    transcriptSource: "unavailable",
    transcriptError: lastError
  };
}

export class YouTubeService {
  constructor(private readonly browserManager: BrowserSessionManager) {}

  async search(runContext: RunContext, query: string, limit: number, sessionId?: string) {
    const page = this.browserManager.getPage(sessionId);
    await page.goto("https://www.youtube.com", { waitUntil: "domcontentloaded" });
    await acceptConsent(page);

    const searchBox = page.locator('input[name="search_query"]').first();
    await searchBox.waitFor({ state: "visible", timeout: 15_000 });
    await searchBox.fill(query);
    await searchBox.press("Enter");

    await page.waitForURL(/results\?search_query=/, { timeout: 15_000 });
    await page.locator("ytd-video-renderer").first().waitFor({ state: "visible", timeout: 15_000 });

    const results = filterOrganicYouTubeResults(await extractSearchResults(page), limit);
    runContext.setState(LAST_SEARCH_RESULTS_KEY, results);

    return results;
  }

  async openResult(
    runContext: RunContext,
    input: { resultIndex?: number; videoUrl?: string; includeTranscript: boolean; sessionId?: string }
  ): Promise<YoutubeVideoArtifact> {
    const page = this.browserManager.getPage(input.sessionId);
    const lastResults = runContext.getState<YoutubeSearchResult[]>(LAST_SEARCH_RESULTS_KEY) ?? [];
    const fallback =
      input.resultIndex !== undefined ? lastResults[input.resultIndex - 1] : undefined;
    const targetUrl = input.videoUrl ?? fallback?.url;

    if (!targetUrl) {
      throw new Error("No YouTube result available for the requested index.");
    }

    await page.goto(targetUrl, { waitUntil: "domcontentloaded" });
    await waitForYouTubeWatchPageReady(page);
    await expandDescription(page);

    const raw = await page.evaluate((fallbackResult) => {
      const pickText = (selectors: string[]): string | null => {
        for (const selector of selectors) {
          const value = document.querySelector(selector)?.textContent?.replace(/\s+/g, " ").trim();
          if (value) {
            return value;
          }
        }
        return null;
      };

      const descriptionCandidates = Array.from(
        document.querySelectorAll("#description-inline-expander, ytd-text-inline-expander, #description")
      )
        .map((element) => element.textContent?.replace(/\s+/g, " ").trim() ?? "")
        .filter(Boolean);
      const publishedCandidates = Array.from(
        document.querySelectorAll("#info-strings yt-formatted-string, #date yt-formatted-string")
      )
        .map((element) => element.textContent?.replace(/\s+/g, " ").trim() ?? "")
        .filter(Boolean);
      const video = document.querySelector("video") as HTMLVideoElement | null;

      return {
        title:
          pickText([
            "ytd-watch-metadata h1 yt-formatted-string",
            "h1.ytd-watch-metadata yt-formatted-string",
            "h1 yt-formatted-string"
          ]) ?? fallbackResult?.title ?? "",
        channel:
          pickText(["ytd-watch-metadata #channel-name a", "#channel-name a", "ytd-video-owner-renderer a"]) ??
          fallbackResult?.channel ??
          null,
        publishedText: publishedCandidates[0] ?? fallbackResult?.publishedText ?? null,
        descriptionText: descriptionCandidates[0] ?? fallbackResult?.descriptionText ?? null,
        durationSeconds:
          video && Number.isFinite(video.duration) ? Math.floor(video.duration) : null
      };
    }, fallback);

    const transcriptText = input.includeTranscript ? await extractTranscript(page) : null;

    return {
      title: raw.title,
      url: page.url(),
      channel: raw.channel,
      publishedText: raw.publishedText,
      durationText:
        raw.durationSeconds !== null
          ? formatDuration(raw.durationSeconds)
          : fallback?.durationText ?? null,
      descriptionText: raw.descriptionText,
      viewsText: fallback?.viewsText ?? null,
      transcriptText
    };
  }

  async collectShorts(
    _runContext: RunContext,
    input: { query?: string; limit: number; sessionId?: string }
  ): Promise<YoutubeShortArtifact[]> {
    const page = this.browserManager.getPage(input.sessionId);
    await openShortsStart(page, input.query);
    await waitForShortsReady(page);

    const shorts: YoutubeShortArtifact[] = [];
    const maxAttempts = input.limit * 3;

    for (let attempt = 0; attempt < maxAttempts && dedupeShorts(shorts).length < input.limit; attempt += 1) {
      const deduped = dedupeShorts(shorts);
      const current = await extractStableActiveShort(page, deduped.length + 1, deduped.at(-1));
      if (current) {
        shorts.push(current);
      }

      if (dedupeShorts(shorts).length >= input.limit) {
        break;
      }

      const previousUrl = page.url();
      await page.keyboard.press("ArrowDown");
      try {
        await page.waitForFunction((url) => window.location.href !== url, previousUrl, {
          timeout: 2_000
        });
        await page.waitForTimeout(700);
      } catch {
        await page.keyboard.press("PageDown");
        await page.waitForTimeout(1_000);
      }
    }

    return dedupeShorts(shorts).slice(0, input.limit);
  }

  async collectShortTranscripts(
    _runContext: RunContext,
    input: { query?: string; limit: number; sessionId?: string; shortUrls?: string[] }
  ): Promise<YoutubeShortTranscriptArtifact[]> {
    const page = this.browserManager.getPage(input.sessionId);
    const transcripts: YoutubeShortTranscriptArtifact[] = [];

    if (input.shortUrls?.length) {
      const shortUrls = input.shortUrls.slice(0, input.limit);
      for (const [index, shortUrl] of shortUrls.entries()) {
        await page.goto(shortUrl, { waitUntil: "domcontentloaded" });
        await acceptConsent(page);
        await waitForShortsReady(page);
        const short =
          (await extractStableActiveShort(page, index + 1, transcripts.at(-1))) ??
          buildShortFromUrl(page.url(), index + 1);
        transcripts.push(await attachShortTranscript(page, short));
      }

      return transcripts;
    }

    await openShortsStart(page, input.query);
    await waitForShortsReady(page);

    const maxAttempts = input.limit * 4;
    for (let attempt = 0; attempt < maxAttempts && dedupeShorts(transcripts).length < input.limit; attempt += 1) {
      const deduped = dedupeShorts(transcripts);
      const current = await extractStableActiveShort(page, deduped.length + 1, deduped.at(-1));
      if (current) {
        transcripts.push(await attachShortTranscript(page, current));
      }

      if (dedupeShorts(transcripts).length >= input.limit) {
        break;
      }

      const previousUrl = page.url();
      await page.keyboard.press("ArrowDown");
      try {
        await page.waitForFunction((url) => window.location.href !== url, previousUrl, {
          timeout: 2_000
        });
        await page.waitForTimeout(700);
      } catch {
        await page.keyboard.press("PageDown");
        await page.waitForTimeout(1_000);
      }
    }

    return dedupeShorts(transcripts).slice(0, input.limit) as YoutubeShortTranscriptArtifact[];
  }
}
